basic/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
          return $this->render('index');
        } else {       
          return $this->render('games');
        }
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionGames()
    {
        if (@$_REQUEST['id']) {
            return $this->refresh();
        } else {
            return $this->render('games');
        }
    }
    
    public function actionFriends()
    {
        return $this->render('friends');
    }
    
    public function actionRanking()
    {
        return $this->render('ranking');
    }
    
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionPost()
    {
        $this->layout = 'post';
        return $this->render('post');
    }
}

basic/views/site/about.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

basic/views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

    <div class="alert alert-success">
        Thank you for contacting us. We will respond to you as soon as possible.
    </div>

    <p>
        Note that if you turn on the Yii debugger, you should be able
        to view the mail message on the mail panel of the debugger.
        <?php if (Yii::$app->mailer->useFileTransport): ?>
        Because the application is in development mode, the email is not sent but saved as
        a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
        Please configure the <code>useFileTransport</code> property of the <code>mail</code>
        application component to be false to enable email sending.
        <?php endif; ?>
    </p>

    <?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <?php endif; ?>
</div>

basic/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

basic/views/site/friends.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'My Friends';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
      <div class="col-md-6">
      <p>
          Choose your friend to play a game with
      </p>
      <?php
        foreach (Yii::$app->user->identity->getFriendsName() as $friends) {
      ?>              
      <p>
        <a class="startgame btn btn-lg btn-success" href="#" 
            data-uid="<?=@Yii::$app->user->identity->id?>"
            data-oid="<?=$friends['id']?>"
            data-unm="<?=@Yii::$app->user->identity->name?>"
            data-onm="<?=$friends['name']?>">
          <?=$friends['name']?>
        </a>
      </p>
      <?php
        }
      ?>                         
      </div>
      <div class="col-md-6">    
              <div id="versus" class="text-center"></div> 
              <div id="board-outer" class="center">
                  <table id="board">
                      <tr class="row">
                          <td class="td" id="a1"></td>
                          <td class="td" id="a2"></td>
                          <td class="td" id="a3"></td>
                      </tr>
                      <tr class="row">
                          <td class="td" id="b1"></td>
                          <td class="td" id="b2"></td>
                          <td class="td" id="b3"></td>
                      </tr>
                      <tr class="row">
                          <td class="td" id="c1"></td>
                          <td class="td" id="c2"></td>
                          <td class="td" id="c3"></td>
                      </tr>
                  </table>
              </div>
              <br>
              <div class="center button">
                  <button id="restart">New game</button>
              </div>         
      </div>
    </div>

</div>

basic/views/site/games.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
$this->title = 'My Games';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-games">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
      <div class="col-md-6">
      <p>
          Select random opponent to start a game
      </p>
      <?php
        foreach (Yii::$app->user->identity->getRandomUserName() as $opp) {
      ?>              
      <p>
        <a class="startgame btn btn-lg btn-success" href="#" 
            data-uid="<?=@Yii::$app->user->identity->id?>"
            data-oid="<?=$opp['id']?>"
            data-unm="<?=@Yii::$app->user->identity->name?>"
            data-onm="<?=$opp['name']?>">
          <?=$opp['name']?>
        </a>
      </p>
      <?php
        }
      ?>                         
      </div>
      <div class="col-md-6">
              <div id="versus" class="text-center"></div> 
              <div id="board-outer" class="center">
                  <table id="board">
                      <tr class="row">
                          <td class="td" id="a1"></td>
                          <td class="td" id="a2"></td>
                          <td class="td" id="a3"></td>
                      </tr>
                      <tr class="row">
                          <td class="td" id="b1"></td>
                          <td class="td" id="b2"></td>
                          <td class="td" id="b3"></td>
                      </tr>
                      <tr class="row">
                          <td class="td" id="c1"></td>
                          <td class="td" id="c2"></td>
                          <td class="td" id="c3"></td>
                      </tr>
                  </table>
              </div>
              <br>
              <div class="center button">
                  <button id="restart">New game</button>
              </div>         
      </div>
    </div>
    <div id="post" data-url="<?=Url::toRoute('/site/post')?>"></div>
</div>

basic/views/site/index - Copy.php
<?php
/* @var $this yii\web\View */
$this->title = 'Online Tic Tac Toe';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

basic/views/site/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Url;
$this->title = 'Online Tic Tac Toe';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Play Now!</h1>

        <p class="lead">Play Online Tic Tac Toe with Your Friends.</p>

        <p><a href="<?=Url::toRoute('/site/login')?>"><img class="img-responsive" style="margin:0 auto;" src="img/t3.jpg"></a></p>
        <p><a class="btn btn-lg btn-success" href="<?=Url::toRoute('/site/login')?>">Login to Play</a></p>
    </div>
</div>

basic/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe', [
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])->checkbox() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <!--<div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>-->
</div>

basic/views/site/post.php
test

basic/views/site/ranking.php
<?php
use yii\helpers\Html;

$scores = new app\models\Scores;
/* @var $this yii\web\View */
$this->title = 'Ranking';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
      <div class="col-md-6">
        <p>
            Your Ranks between Friends
        </p>        
        <div class="table-responsive">
          <table class="table table-striped dt-right compact">
          <thead>
            <tr>
              <th>#</th>
              <th>name</th>
              <th>score</th>
            </tr>
          </thead>
          <tbody>
          <?php            
            $i=0;
            $uid=array();
            foreach (Yii::$app->user->identity->getMeNFriends() as $mnf) {
              $uid[$i] = $mnf['id'];
              $i++;
            }
            $j=0;
            foreach ($scores->getScore($uid) as $rank) {
          ?>  
            <tr class="<?=($rank->id==Yii::$app->user->identity->id)?'info text-info':''?>">    
              <td><?=$j+1?></td>
              <td><?=Yii::$app->user->identity->findIdentity($rank->id)->name?></td>
              <td><?=$rank->score?></td>
            </tr> 
          <?php
              $j++;
            }
          ?> 
          </tbody>  
          </table>                     
        </div>                    
      </div>
    </div>

</div>